### ISSUE TITLE
Use the new ScoreResult api

### ISSUE THREAD

**Issue by nicojs** [riezebosch/stryker-baseline-reporter#1]
We recently added a reporter callback function [`onScoreCalculated`](https://github.com/stryker-mutator/stryker/blob/master/packages/stryker-api/src/report/Reporter.ts#L45). It reports the mutation score directly, without you having to calculate it yourself in every reporter.

It would be nice of the baseline reporter uses that API.

**Comment by riezebosch** [comment]
But how could it? The reporter is storing and comparing actual mutants and the onScoreCalculated only seems to provide numbers without any context.

**Comment by nicojs** [comment]
Ah true. I thought you also did something with the score, to see if the score was better/worse than last run. My bad.
